import subprocess

def install_rds():
    powershell_command = 'Install-WindowsFeature -Name RDS-RD-Server -IncludeAllSubFeature -IncludeManagementTools'
    
    try:
        # Run PowerShell command with administrator privileges
        result = subprocess.run(["powershell", "-Command", powershell_command], capture_output=True, text=True, check=True)
        print("RDS Installation Output:", result.stdout)
    except subprocess.CalledProcessError as e:
        print("Error installing RDS:", e.stderr)

if __name__ == "__main__":
    install_rds()
